CREATE DATABASE Universidade;
GO

USE Universidade;
GO

-- TABELA ALUNOS------------------------------------------------------------
CREATE TABLE ALUNOS
(
	MATRICULA INT NOT NULL IDENTITY
		CONSTRAINT PK_ALUNO PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
GO

-- TABELA CURSOS---------------------------------------------------------------------
CREATE TABLE CURSOS
(
	CURSO CHAR(3) NOT NULL
		CONSTRAINT PK_CURSO PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
GO

-- TABELA PROFESSORES---------------------------------------------------------
CREATE TABLE PROFESSOR
(
	PROFESSOR INT IDENTITY NOT NULL
		CONSTRAINT PK_PROFESSOR PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
GO

-- TABELA MATERIAS---------------------------------------------------------------
CREATE TABLE MATERIAS
(
	SIGLA CHAR(3) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CARGAHORARIA INT NOT NULL,
	CURSO CHAR(3) NOT NULL,
	PROFESSOR INT NOT NULL,

	CONSTRAINT PK_MATERIA 
		PRIMARY KEY (SIGLA, CURSO, PROFESSOR),
	CONSTRAINT FK_CURSO 
		FOREIGN KEY (CURSO) 
		REFERENCES CURSOS (CURSO),
	CONSTRAINT FK_PROFESSOR 
		FOREIGN KEY (PROFESSOR) 
		REFERENCES PROFESSOR (PROFESSOR)
);
GO

-- TABELA MATRICULA----------------------------------------------------------
CREATE TABLE MATRICULA
(
	MATRICULA INT,
	CURSO CHAR(3),
	MATERIA CHAR(3),
	PROFESSOR INT,
	PERLETIVO INT,
	N1 FLOAT,
	N2 FLOAT,
	N3 FLOAT,
	N4 FLOAT,
	N5 FLOAT,
	TOTALPONTOS FLOAT,
	MEDIA FLOAT,
	F1 INT,
	F2 INT,
	F3 INT,
	F4 INT,
	TOTALFALTAS INT,
	PERCFREQ FLOAT,
	RESULTADO VARCHAR(20),
	MEDIAFINAL FLOAT,
	NOTAEXAME FLOAT,

	CONSTRAINT PK_MATRICULA PRIMARY KEY (
		MATRICULA,
		CURSO,
		MATERIA,
		PROFESSOR,
		PERLETIVO
	),
	CONSTRAINT FK_ALUNOS_MATRICULA 
		FOREIGN KEY (MATRICULA) 
		REFERENCES ALUNOS (MATRICULA),
	CONSTRAINT FK_CURSOS_MATRICULA 
		FOREIGN KEY (CURSO) 
		REFERENCES CURSOS (CURSO),
	CONSTRAINT FK_PROFESSOR_MATRICULA 
		FOREIGN KEY (PROFESSOR) 
		REFERENCES PROFESSOR (PROFESSOR),
	CONSTRAINT FK_MATERIAS 
		FOREIGN KEY (MATERIA, CURSO, PROFESSOR)
		REFERENCES MATERIAS (SIGLA, CURSO, PROFESSOR)
);
GO
------------------------------------------------------------------------------------------
-- INSERINDO ALUNOS
INSERT INTO ALUNOS (NOME) 
	VALUES ('Pedro'), 
		('Robertha');
GO

-- INSERINDO CURSOS--------------------------------------------------------------------
INSERT INTO CURSOS (CURSO, NOME) VALUES
('SIS', 'SISTEMAS'),
('ENG', 'ENGENHARIA');
GO

-- INSERINDO PROFESSORES---------------------------------------------------------------
INSERT INTO PROFESSOR (NOME) 
	VALUES
	('DORNEL'), 
	('EDUARDO'), 
	('KARLA'),
	('CHAIENE'), 
	('LEANDERSON'), 
	('ROMÃO');
GO

-- INSERINDO MATERIAS COM UMA VERIFICAÇÃO QUE EVITA A DUPLICIDADE---------------------------------------------------------------------------
IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'BDA' AND CURSO = 'ENG' AND PROFESSOR = 1)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'BDA', 
		'BANCO DE DADOS', 
		144, 
		'ENG', 
		1);
END

IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'ARC' AND CURSO = 'ENG' AND PROFESSOR = 2)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'ARC', 
		'ARQUITETURA DE COMPUTADORES', 
		144, 
		'ENG', 
		2);
END

IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'EIX' AND CURSO = 'ENG' AND PROFESSOR = 3)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'EIX', 
		'EIXO INSTITUCIONAL', 
		144, 
		'ENG', 
		3);
END

IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'ER' AND CURSO = 'ENG' AND PROFESSOR = 4)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'ER', 
		'ENGENHARIA DE REQUISITOS DE SOFTWARE', 
		144, 
		'ENG',
		4);
END

IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'POO' AND CURSO = 'ENG' AND PROFESSOR = 5)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'POO', 
		'PROGRAMAÇÃO 
		ORIENTADA A OBJETO', 
		144, 
		'ENG', 
		5);
END

IF NOT EXISTS(SELECT 1 FROM MATERIAS WHERE SIGLA = 'VEI' AND CURSO = 'ENG' AND PROFESSOR = 6)
BEGIN
	INSERT INTO MATERIAS (
		SIGLA, 
		NOME, 
		CARGAHORARIA, 
		CURSO, 
		PROFESSOR)
	VALUES (
		'VEI', 
		'VIVÊNCIA DE EXTENSÃO', 
		144, 
		'ENG', 
		6);
END
GO

--MATRÍCULA PARA PEDRO | Informações------------------------------------------------------------
INSERT INTO MATRICULA (
	MATRICULA, 
	CURSO, 
	MATERIA, 
	PROFESSOR, 
	PERLETIVO,
	N1, 
	N2, 
	N3, 
	N4, 
	N5,
	TOTALPONTOS, 
	MEDIA,
	F1, 
	F2, 
	F3, 
	F4, 
	TOTALFALTAS, 
	PERCFREQ,
	RESULTADO, 
	MEDIAFINAL, 
	NOTAEXAME
)
VALUES (
	2, 
	'ENG', 
	'BDA', 
	5, 
	20241,
	8.0, 
	9.0, 
	7.5, 
	10.0, 
	NULL,        -- N5
	34.5,          
    8.625, 
	0, 
	1, 
	2, 
	0, 
	3, 
	97.0,
	'REPROVADO', 
	NULL, 
	NULL
);

--MATRÍCULA PARA ROBERTHA | Informações--------------------------------------------------------------
INSERT INTO MATRICULA (
	MATRICULA, 
	CURSO, 
	MATERIA, 
	PROFESSOR, 
	PERLETIVO,
	N1, 
	N2, 
	N3, 
	N4, 
	N5,
	TOTALPONTOS, 
	MEDIA,
	F1, 
	F2, 
	F3, 
	F4, 
	TOTALFALTAS, 
	PERCFREQ,
	RESULTADO, 
	MEDIAFINAL, 
	NOTAEXAME
)
VALUES (
	2, 
	'ENG', 
	'POO', 
	5, 
	20241,
	8.0, 
	1.0, 
	5.5, 
	10.0, 
	NULL,        -- N5
	24.5, 
	6.125,
	0, 
	1, 
	2, 
	0, 
	3, 
	97.0,
	'REPROVADO', 
	NULL, 
	NULL
);


---SELECT PARA CADA TABELA-----------------------------------------------------
SELECT * FROM ALUNOS
SELECT * FROM PROFESSOR
SELECT * FROM MATERIAS
SELECT * FROM MATRICULA
SELECT * FROM CURSOS




