CREATE DATABASE TURMA;
CREATE TABLE ALUNOS
(
    MATRICULA INT CONSTRAINT PK_ALUNOS PRIMARY KEY,
    NOME CHAR(50)
)
INSERT ALUNOS (MATRICULA,NOME) VALUES (1,'ROBERTHA')
ALTER TABLE ALUNOS ADD DATANASCIMENTO DATE 
UPDATE ALUNOS
SET DATANASCIMENTO = '2004-11-14'
WHERE MATRICULA = 1
SELECT * FROM ALUNOS
