CREATE DATABASE TURMA1442AN;

USE TURMA1442AN;

CREATE TABLE ALUNOS
(
    MATRICULA CHAR(10) CONSTRAINT PK_ALUNOS PRIMARY KEY,
    NOME CHAR(10),
    SOBRENOME CHAR(10)
)
INSERT ALUNOS(MATRICULA,NOME,SOBRENOME)
    VALUES('RA1234','ROBERTHA','REZENDE')

INSERT ALUNOS(NOME,SOBRENOME,MATRICULA) 
VALUES('ROBERTHA1','REZENDE1','RA12341')

SELECT * FROM ALUNOS 
DELETE FROM ALUNOS WHERE MATRICULA = 'REZENDE'

ALTER TABLE ALUNOS ADD SEXO CHAR(1)

UPDATE ALUNOS SET SEXO = 'F', NOME='GISELE' 
WHERE MATRICULA = 'RA1234' AND SOBRENOME = 'REZENDE'

UPDATE ALUNOS SET SEXO = 'F', NOME='ROBERTHA' 
WHERE MATRICULA = 'RA1234' AND SOBRENOME = 'REZENDE'

UPDATE ALUNOS SET NOME = 'ROBERTHA'
WHERE MATRICULA = 'RA1235' 

CREATE TABLE GENERO
(
    SEXO CHAR(1),
    DESCRICAO CHAR(10)
)

INSERT GENERO (SEXO,DESCRICAO) VALUES('F','FEMININO')
INSERT GENERO (SEXO,DESCRICAO) VALUES('M','MASCULINO')

SELECT ALUNOS.NOME, ALUNOS.SOBRENOME, GENERO.SEXO,
GENERO.DESCRICAO
FROM ALUNOS, GENERO
WHERE ALUNOS.SEXO=GENERO.SEXO