CREATE DATABASE CLINICAV; 
USE CLINICAV;

DROP TABLE CLINICAV
CREATE TABLE CLINICAV 
( 
 CNPJ CHAR(20) CONSTRAINT PK_CLINICAV PRIMARY KEY,  
 NOME CHAR(50),  
 ENDEREÇO CHAR(100),  
); 

INSERT CLINICAV(CNPJ, NOME, ENDEREÇO) 
VALUES('12.345.678/0001-95', 'CLINICA V', 'RUA 10');
SELECT * FROM CLINICAV


CREATE TABLE ATENDIMENTO 
( 
 VALOR CHAR(20),  
 DATA_AT CHAR(20),  
 COD_ANIMAL CHAR(50),  
 CLIENTE CHAR(100),  
 COD_FUN CHAR(50),  
 COD_ATD CHAR(20) CONSTRAINT PK_ATENDIMENTO PRIMARY KEY, 
 CNPJ CHAR(14) 
);

INSERT ATENDIMENTO (VALOR, DATA_AT, COD_ANIMAL, CLIENTE, CNPJ, COD_FUN, COD_ATD) 
VALUES ('0000', '18/10/2024', '101420', 'ROBERTHA', '10142000000195', 'FUN1452', 'AT1020');
SELECT * FROM ATENDIMENTO


CREATE TABLE FUNCIONARIO 
( 
 COD_FUN CHAR(20) CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,  
 NOME CHAR(100),  
 DATA_CONTRA CHAR(20),  
); 

INSERT FUNCIONARIO (COD_FUN, NOME, DATA_CONTRA) 
VALUES ('FUN1452', 'RENATA', '15/01/2023');
SELECT * FROM FUNCIONARIO


CREATE TABLE CLIENTE 
( 
 NOME CHAR(100),  
 COD_CLIENTE CHAR(20) CONSTRAINT PK_CLIENTE PRIMARY KEY,  
); 
INSERT CLIENTE (NOME, COD_CLIENTE)
VALUES ('ROBERTHA', 'CLI141104')
SELECT * FROM CLIENTE

CREATE TABLE ANIMAL 
( 
 COD_RAÇA CHAR(100),  
 NOME CHAR(50),  
 COD_CLIENTE CHAR(50),  
 COD_ANIMAL CHAR(20) CONSTRAINT PK_ANIMAL PRIMARY KEY,  
); 
INSERT ANIMAL (COD_RAÇA, NOME, COD_ANIMAL, COD_CLIENTE)
VALUES ('RAÇA', 'CACHORRO', 'ANI123', 'CLI456')
SELECT * FROM ANIMAL

CREATE TABLE RAÇA 
( 
 COD_RAÇA CHAR(20) CONSTRAINT PK_RAÇA PRIMARY KEY,  
 DESCRIÇÃO CHAR(500),  
); 
INSERT RAÇA (COD_RAÇA, DESCRIÇÃO)
VALUES ('RA789', 'CACHORRO')
SELECT * FROM RAÇA


ALTER TABLE ATENDIMENTO 
ADD FOREIGN KEY (CNPJ) REFERENCES CLINICA (CNPJ); 
ALTER TABLE ANIMAL 
ADD FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);
ALTER TABLE ANIMAL 
ADD FOREIGN KEY (COD_RAÇA) REFERENCES RAÇA (COD_RAÇA); 
