CREATE TRIGGER trgUPDATE_Clientes
ON Clientes
FOR UPDATE
AS 
BEGIN
    INSERT ClienteCodigo SELECT *,[TRG_OPERACAO] = 'UPDATE',[TRG_DATA]=GETDATE(),[TRG_FLAG]='OLD' FROM Deleted
    INSERT ClienteCodigo SELECT *,[TRG_OPERACAO] = 'UPDATE',[TRG_DATA]=GETDATE(),[TRG_FLAG]='NEW' FROM Inserted
END