CREATE DATABASE locadora;
USE locadora;
CREATE TABLE locadora 
( 
 CNPJ INT CONSTRAINT PK_locadora PRIMARY KEY,  
 NOMEFANT CHAR(100),  
); 
INSERT locadora(CNPJ, NOMEFANT) VALUES(5678, 'LOCADORA01')
SELECT * FROM locadora

CREATE TABLE funcionario 
( 
 MATRICULA INT CONSTRAINT PK_funcionario  PRIMARY KEY,  
 SEXO CHAR CONSTRAINT CHECK_SEXO CHECK(SEXO IN ('M', 'F')),
 NOME CHAR(50),  
 DTNASC DATE,  
 CNPJ INT,  
); 

ALTER TABLE funcionario ADD FOREIGN KEY(CNPJ) REFERENCES locadora (CNPJ)

INSERT funcionario (MATRICULA,NOME,DTNASC,SEXO,CNPJ)
VALUES (1,'DORNEL','2000-01-01','M',12345)
SELECT * FROM funcionario